function loadLcdDigits() {
    return [
        {
            digit:'0',
            firstLine:'._.',
            secondLine:'|.|',
            thirdLine:'|_|'
        },
        {
            digit:'1',
            firstLine:'...',
            secondLine:'..|',
            thirdLine:'..|'
        },
        {
            digit:'2',
            firstLine:'._.',
            secondLine:'._|',
            thirdLine:'|_.'
        },
        {
            digit:'3',
            firstLine:'._.',
            secondLine:'._|',
            thirdLine:'._|'
        },
        {
            digit:'4',
            firstLine:'...',
            secondLine:'|_|',
            thirdLine:'..|'
        },
        {
            digit:'5',
            firstLine:'._.',
            secondLine:'|_.',
            thirdLine:'._|'
        },
        {
            digit:'6',
            firstLine:'._.',
            secondLine:'|_.',
            thirdLine:'|_|'
        },
        {
            digit:'7',
            firstLine:'._.',
            secondLine:'..|',
            thirdLine:'..|'
        },
        {
            digit:'8',
            firstLine:'._.',
            secondLine:'|_|',
            thirdLine:'|_|'
        },
        {
            digit:'9',
            firstLine:'._.',
            secondLine:'|_|',
            thirdLine:'..|'
        }
    ];
}